# Generated by Django 2.2.1 on 2019-12-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymessage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
