# Generated by Django 2.2.1 on 2019-12-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymessage', '0002_message_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
